CREATE TABLE Genesis  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Exodus  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Leviticus  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Numbers  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Deuteronomy  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Joshua  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Judges  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Ruth  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE OneSam  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE TwoSam  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE OneKing  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE TwoKing  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE OneChr  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE TwoChr  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Ezra  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Nehemiah  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Esther  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Job  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Psalms  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Proverbs  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Ecclesiastes  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE SOS  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Isaiah  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Jeremiah  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Lamentations  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Ezekiel  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Daniel  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Hosea  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Joel  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Amos  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Obadiah  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Jonah  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Micah  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Nahum  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Habakkuk  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Zephaniah  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Haggai  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Zechariah  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Malachi  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Matthew  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Mark  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Luke  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE John  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Acts  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Romans  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE OneCor  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE TwoCor  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Galatians  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Ephesians  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Philippians  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Colossians  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE OneThes  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE TwoThes  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE OneTim  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE TwoTim  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Titus  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Philemon  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Hebrews  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE James  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE OnePeter  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE TwoPeter  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Jude  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE Revelation  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE OneJohn  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE TwoJohn  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE ThreeJohn  (Chapter integer KEY,Verse integer KEY,WordSeqNumber integer,Word varchar,pre varchar,post varchar,WordFormat integer, OrigWordLanguage char(1), DictEntryNumber integer);
CREATE TABLE copyright(CopyrightInfo text);
CREATE TABLE TESTTYPE  (BookShortName text primary key not null,Book text key,TSTMT text);
CREATE TABLE FootNoteTable(FtnNmbr integer primary Key not null,BookNumber integer,Chapter integer,Verse integer,WordSeqNumber integer,Word varchar);
CREATE UNIQUE INDEX ExodusIDX on Exodus(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE TABLE Title(TitleColumn varchar);
CREATE INDEX LeviticusIDX on Leviticus(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX RuthIDX on Ruth(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX DeuteronomyIDX on Deuteronomy(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX JoshuaIDX on Joshua(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX JudgesIDX on Judges(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX MatthewIDX on Matthew(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX OneSamIDX on OneSam(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX TwoSamIDX on TwoSam(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX OneKingIDX on OneKing(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX OneChrIDX on OneChr(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX TwoChrIDX on TwoChr(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX EzraIDX on Ezra(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX EstherIDX on Esther(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX FootNoteTableIDX on FootNoteTable(BookNumber ASC,Chapter ASC,Verse ASC,WordSeqNumber ASC);
CREATE INDEX NehemiahIDX on Nehemiah(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX JobIDX on Job(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX PsalmsIDX on Psalms(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX ProverbsIDX on Proverbs(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX EcclesiastesIDX on Ecclesiastes(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX SOSIDX on SOS(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX IsaiahIDX on Isaiah(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX HoseaIDX on Hosea(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX JoelIDX on Joel(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX JeremiahIDX on Jeremiah(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX LamentationsIDX on Lamentations(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX JudeIDX on Jude(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX OneTimIDX on OneTim(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX EzekielIDX on Ezekiel(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX MalachiIDX on Malachi(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX DanielIDX on Daniel(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX AmosIDX on Amos(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX ObadiahIDX on Obadiah(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX JonahIDX on Jonah(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX MicahIDX on Micah(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX HabakkukIDX on Habakkuk(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX NahumIDX on Nahum(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX ZephaniahIDX on Zephaniah(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX HaggaiIDX on Haggai(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX ZechariahIDX on Zechariah(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX TwoKingIDX on TwoKing(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX MarkIDX on Mark(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX PhilippiansIDX on Philippians(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX NumbersIDX on Numbers(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX GalatiansIDX on Galatians(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX JohnIDX on John(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX ActsIDX on Acts(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX RomansIDX on Romans(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX OneCorIDX on OneCor(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX TwoCorIDX on TwoCor(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX EphesiansIDX on Ephesians(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX ColossiansIDX on Colossians(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX OneThesIDX on OneThes(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX TwoThesIDX on TwoThes(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX TwoTimIDX on TwoTim(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX TitusIDX on Titus(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX PhilemonIDX on Philemon(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX OneJohnIDX on OneJohn(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX TwoJohnIDX on TwoJohn(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX ThreeJohnIDX on ThreeJohn(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX HebrewsIDX on Hebrews(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX JamesIDX on James(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX TwoPeterIDX on TwoPeter(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX RevelationIDX on Revelation(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX LukeIDX on Luke(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX OnePeterIDX on OnePeter(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
CREATE INDEX GenesisIDX on Genesis(Chapter ASC ,Verse ASC ,WordSeqNumber ASC);
